PREFIX nl: <http://purl.org/nutrilink#>

select ?basketNutriScoreCalculated ?basketOfComValue ?basketTimestamp
where
{
    ?userData fc:externalId "USER_IDENTIFIER";
        fc:segmentId "SEGMENT_ID";
        fc:isOfUser ?user.

    ?user fc:buysBasket ?basket.

    ?basket fc:timestamp ?basketTimestamp.
        
    ?basketAggInfo fc:containsInformationOfBasket ?basket;
        fc:containsNutritionInformation ?basektOfComDetail;
        fc:containsNutritionInformation ?basketNutriScore.

    # remove invalid data
    ?basketNutriScore fc:nutriScoreCalculated ?basketNutriScoreCalculated filter (?basketNutriScoreCalculated != "F").
    ?basektOfComDetail fc:ofComValue ?basketOfComValue filter (?basketOfComValue != -20).
}
ORDER BY DESC(?basketTimestamp)
LIMIT NUMBEROFBASKET